# Generated by Django 4.1 on 2022-09-02 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_delete_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('time_out', models.DateTimeField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
