# Generated by Django 4.1 on 2022-09-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_codemodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
